### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory pokemon.json

### ISSUE THREAD

**Issue by nioperas06** [mirzal/create-pokemon-team#19]
Thanks for contributing to createPokémon.team!

Questions below are here to get you started. You may answer as many of them as you like, or none at all. Feel free to remove everything that does not apply to your situation, including this message.

# What kind of issue that is?

- [ ] a bug report
- [ ] a new feature request
- [ ] a question

# Short description of your issue
Just trying to run the backend:

`$ ./run.py`

FileNotFoundError: [Errno 2] No such file or directory: '.../create-pokemon-team/backend
/api/data/pokemon.json'

# What have you done before encountering the problem? It's better to give too many details than miss something important

# What did you expect to happen?

# What happened instead?

**Comment by mirzal** [comment]
Hi @nioperas06 , thanks for showing interest in this project.

I believe that the root cause of your problem is that you haven't run `pokedexreader` before running `./run.py`. You have to run `pokedexreader` to create data files that will be loaded by backend. This is intentional, as I do not want to store any Pokemon data inside this repo. 

Have you tried following instructions in `/data-manager/README.md`? You first need to get data from Eevee Pokedex (following instructions in my README should be enough) and then run:

```
pokedexreader --eevee <path_to_veekun_pokedex.sqlite> -o ../backend/api/data/
```

Hope that helps.
